# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160901_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuildtests',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date published'),
        ),
    ]
