# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_titre', models.CharField(default=b'', max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date published')),
                ('photo', models.ImageField(default=b'', upload_to=b'diapo/')),
            ],
        ),
    ]
