# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160902_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='windsurf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windsurf_titre', models.CharField(default=b'', max_length=100)),
                ('windsurf_description', models.TextField(blank=True)),
                ('windsurf_text', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date published')),
                ('photo', models.ImageField(default=b'', upload_to=b'photos/')),
                ('windsurf_video', models.TextField(blank=True)),
            ],
        ),
    ]
