# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_windsurf'),
    ]

    operations = [
        migrations.CreateModel(
            name='windsurfImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'photos/')),
                ('produit', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='polls.produit')),
            ],
        ),
    ]
