# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_windsurfimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windsurfimage',
            name='produit',
        ),
        migrations.AddField(
            model_name='windsurfimage',
            name='windsurf',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='polls.windsurf'),
        ),
    ]
